"""
Django settings for gut_auth project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2l7c5y*htbt4(7zudkno5^ax&^a%w@k8*+liik9wuj3w@u-04w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'fasta_processor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gut_auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
TEMPLATES[0]['DIRS'] = [BASE_DIR / "templates"]

WSGI_APPLICATION = 'gut_auth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
        
#         'ENGINE': 'mssql',

#         'NAME': 'gut_health_db',
#         'HOST': 'DESKTOP-VN2I5D3',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 18 for SQL Server',
#             'trusted_connection': 'yes',
#             'extra_params': 'Encrypt=yes;TrustServerCertificate=yes;',
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production
# Only include static directory if it exists (to avoid warnings)
STATICFILES_DIRS = []
static_dir = BASE_DIR / 'static'
if static_dir.exists():
    STATICFILES_DIRS.append(static_dir)

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# EGGNOG Database Path (WSL path)
EGGNOG_DB_PATH = Path('/home/ser1dai/eggnog_db_final')

# KOFAM Database Path (WSL path)
KOFAM_DB_PATH = Path('/home/ser1dai/eggnog_db_final/kofam_db')

# FASTA Processing Resource Configuration
# Optimized for 16 GB RAM system: using 12 GB RAM and 4 CPU cores for fast processing
FASTA_PROCESSING_CPU_CORES = 4  # Number of CPU cores to use (1-4, higher = faster processing)
                                 # Set to 4 for maximum performance on 4-core systems
FASTA_PROCESSING_RAM_GB = 12  # RAM limit in GB for FASTA processing
                               # Set to 12 GB to use most of available 16 GB RAM for fast processing
FASTA_PROCESSING_USE_NICE = True  # Use 'nice' command to lower process priority (prevents system hang)
                                   # Set to False if 'nice' command is not available
FASTA_PROCESSING_NICE_VALUE = 10  # Nice value (0-19, higher = lower priority, less CPU usage)
                                   # Recommended: 10-15 for background processing

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# For development: Use console backend (emails print to terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production: Use SMTP backend to send real emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # For Gmail. Use 'smtp-mail.outlook.com' for Outlook
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Use TLS for Gmail. Use EMAIL_USE_SSL = True for some providers
EMAIL_HOST_USER = 'your-email@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'your-app-password'  # Your email password or app password
DEFAULT_FROM_EMAIL = 'your-email@gmail.com'  # Default sender email

# Note: For Gmail, you need to:
# 1. Enable 2-factor authentication
# 2. Generate an "App Password" (not your regular password)
# 3. Use that app password in EMAIL_HOST_PASSWORD
# Go to: Google Account > Security > 2-Step Verification > App passwords

LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'fasta_processor': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
