# Generated by Django 5.2.9 on 2025-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasta_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='progress',
            field=models.IntegerField(default=0, help_text='Processing progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Current processing step message', max_length=255),
        ),
    ]
