# Generated by Django 5.2.9 on 2026-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasta_processor', '0003_processingjob_pathway_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='tpm_file',
            field=models.FileField(blank=True, help_text='RNA TPM expression table (gene_id, TPM)', null=True, upload_to='tpm_tables/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='result_file',
            field=models.FileField(blank=True, help_text='Enzyme-level results CSV file', null=True, upload_to='results/%Y/%m/%d/'),
        ),
    ]
